### PR TITLE
fix the layout

### PR DESCRIPTION
**Pull request by Emily-Jiang**

### CODE REVIEW

**Comment by kazumura** [comment]
@Emily-Jiang   
Please also change the followings:

* change 'anchor:' to link to section
```
   *   A statement that the anchor:_certification_of_compatibility[Certification of
       Compatibility] process must be
```
-->
```
    *   A statement that the <<_certification_of_compatibility>> process must be
```

* remove redundant back slash
```
section labeled \"Additional Certification Requirements\".
```
-->
```
section labeled "Additional Certification Requirements".
```

**Comment by Emily-Jiang** [comment]
@kazumura I have made the above requested updates. Thank you for pointing them out! Please approve if you don't have any further comments.

**Comment by kazumura** [comment]
Thanks @Emily-Jiang . I approve. But It seems that I don't have the privilege to approve in this repo.

**Comment by Emily-Jiang** [comment]
@kazumura please add a comment [here](https://github.com/microprofile/microprofile-wg/issues/122) to say you would like to be added.

**Pull request merged**
