### PR TITLE
Updated MPSP to version 1.1

### PR DESCRIPTION
**Pull request by jclingan**
Pull request for the MicroProfile Specification Process 1.1 Steering Committee ballot

### CODE REVIEW

**Comment by aeiras** [comment]
It reads great, @jclingan :)

**Review by ederks85 — APPROVED** [review]

**Review by emecas — COMMENTED** [review]
LGTM

**Comment by jclingan** [comment]
Ballot passed: https://www.eclipse.org/lists/microprofile-wg/msg01630.html

**Comment by edbratt** [comment]
I'm not sure what has gone wrong but the rendering of the v1.2 of this document does not appear to be generating link text as expected for an AsciiDoctor file. It would be nice if this could be corrected when this document is merged. (See: https://microprofile.io/microprofile-specification-process/)

**Comment by jclingan** [comment]
Thanks Ed. We'll look into it.

**Comment by jclingan** [comment]
Ok, it looks like the formatting is correct in the asciidoc. I think the issue is with how it was pulled into  microprofile.io. We'll do some due diligence on the formatting at microprofile.io. Thanks for the heads up.

**Pull request merged**
